### ISSUE TITLE
Lists not displayed correctly in rendered markdown

### ISSUE THREAD

**Issue by SteveHartzog** [SteveHartzog/blog#2]
Lists are bunched together. Source needs \n, but even then:

"1. Blah"
"1. Blah2"

Should render as:

1. Blah
1. Blah2

**Comment by charlie8230** [comment]
Strings need to be properly escaped in the firebase JSON and this works correctly.  I think we can close this,

**Comment by SteveHartzog** [comment]
@charlie8230, could you commit what you have or send it over?

**Comment by charlie8230** [comment]
See above comment... when adding the blog entry data in firebase we need to make sure that strings are properly escaped in JSON.  We can close :)
