### ISSUE TITLE
Add Highlight.js code formatting

### ISSUE THREAD

**Issue by SteveHartzog** [SteveHartzog/blog#3]
See the usage examples for `highlight.js`: https://github.com/markdown-it/markdown-it#usage-examples

Add a default theme and a new configuration element. According to @EisenbergEffect: 

> I believe the theme’s code highlight is coming from https://craig.is/making/rainbows

**Comment by SteveHartzog** [comment]
@charlie8230, could you commit what you have or send it over?

**Comment by charlie8230** [comment]
Hey @SteveHartzog - this was completed under the blog-3 branch... I can mark this issue as completed but I'll defer to you

**Comment by SteveHartzog** [comment]
Closed by commit 8a0513cd4a44d29fea2dc407b75e40e0bd615436
